Repository rilling/jmonkeyengineFall2024, pull requests merged in 2024-11, with the labels that each got.

#87 Clone AndroidJoystickJoyInput14.java - logger and Clone JmeSurfaceView.java - loseFocus() - gainFocus()
  jme3-android/src/main/java/com/jme3/input/android/AndroidJoystickJoyInput14.java
  jme3-android/src/main/java/com/jme3/view/surfaceview/JmeSurfaceView.java
Labels: Group 3, Removing Software Clones

#71 Group 4 removing software clones
  jme3-android/src/main/java/com/jme3/audio/plugins/NativeVorbisLoader.java
  jme3-android/src/main/java/com/jme3/input/android/AndroidGestureProcessor.java
  jme3-android/src/main/java/com/jme3/input/android/AndroidInputHandler.java
  jme3-android/src/main/java/com/jme3/input/android/AndroidInputHandler14.java
  jme3-android/src/main/java/com/jme3/renderer/android/RendererUtil.java
Labels: Group 4, Removing Software Clones

#102 Group 6 Clone fixes - Case Study 2
  jme3-desktop/src/main/java/com/jme3/app/state/MjpegFileWriter.java
  jme3-desktop/src/main/java/com/jme3/input/awt/AwtKeyInput.java
  jme3-desktop/src/main/java/com/jme3/input/awt/AwtMouseInput.java
  jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java
  jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java
Labels: Group 6, Removing Software Clones

#109 Group 05 - Case Study 2
  jme3-desktop/src/main/java/com/jme3/app/state/AWTComponentAppState.java
  jme3-desktop/src/main/java/com/jme3/app/state/MjpegFileWriter.java
  jme3-desktop/src/main/java/com/jme3/cursors/plugins/CursorLoader.java
  jme3-desktop/src/main/java/com/jme3/system/AWTComponentRenderer.java
  jme3-desktop/src/main/java/com/jme3/texture/plugins/AWTLoader.java
Labels: Group 5, Removing Software Clones
