Repository rilling/jmonkeyengineFall2024, pull requests merged in 2024-12, with the labels that each got.

#140 Vulnerability fix134
  jme3-android/src/main/java/com/jme3/audio/plugins/NativeVorbisLoader.java
Labels: Group 3, Remove Software Vulnerability

#150 Vulnerability148
  jme3-plugins/src/xml/java/com/jme3/export/xml/XMLImporter.java
Labels: Group 3, Remove Software Vulnerability

#161 Merge for Group 7, Removing vulnerabilities for Case Study 3
  jme3-desktop/src/main/java/com/jme3/app/state/VideoRecorderAppState.java
  jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java
  jme3-networking/src/main/java/com/jme3/network/kernel/tcp/SocketConnector.java
Labels: Group 7, Remove Software Vulnerability

#163 Vulnerability#162 - RendererUtil.ENABLE_ERROR_CHECKING isn't final but should be
  jme3-android/src/main/java/com/jme3/renderer/android/RendererUtil.java
Labels: Group 3, Remove Software Vulnerability

#167 Vulnerability fix issue #158 - Refactor RotationOrder enum to fix mutable static field vulnerability.
  jme3-android/src/main/java/com/jme3/app/AndroidHarness.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/RotationOrder.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxNode.java
Labels: Group 3, Remove Software Vulnerability

#173 Group 4 - software vulnerabilities resolution
  jme3-android/src/main/java/com/jme3/app/state/MjpegFileWriter.java
  jme3-android/src/main/java/com/jme3/input/android/AndroidInputHandler.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
  jme3-core/src/tools/java/jme3tools/shadercheck/GpuAnalyzerValidator.java
  jme3-networking/src/main/java/com/jme3/network/kernel/tcp/SocketConnector.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/XMLImporter.java
Labels: Group 4, Remove Software Vulnerability

#174 PR for group 6 software vulnerabilities
  build.gradle
  jme3-core/src/main/java/com/jme3/environment/util/EnvMapUtils.java
  jme3-core/src/main/java/com/jme3/shader/ShaderGenerator.java
  jme3-core/src/main/java/com/jme3/shader/ShaderUtils.java
  jme3-desktop/src/main/java/com/jme3/app/state/MjpegFileWriter.java
  jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java
  jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java
Labels: Group 6, Remove Software Vulnerability

#176 Group 5 - Case Study 3
  build.gradle
  jme3-android/src/main/java/com/jme3/input/android/AndroidInputHandler.java
  jme3-desktop/src/main/java/com/jme3/app/AppletHarness.java
  jme3-desktop/src/main/java/com/jme3/app/state/MjpegFileWriter.java
  jme3-desktop/src/main/java/com/jme3/app/state/VideoRecorderAppState.java
  jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java
Labels: Group 5, Remove Software Vulnerability
